site_name: "DnFreddie Notes"
site_url: "https://defnotnotes.com/"
repo_name: "DnFreddie/DnFreddie"
repo_url: "https://github.com/DnFreddie/"

docs_dir: "docs"  
site_dir: "public"

extra_css:
  - assets/custom.css

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.sections
    - navigation.footer
    - navigation.tabs
    - content.tags
  font:
    text: JetBrains Mono
  palette:
    scheme: slate
    primary: black
    accent: cyan

markdown_extensions:
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
  - attr_list
  - md_in_html

plugins:
  - search
  - tags:
      tags_file: tags.md  

  - blog:
      draft: false
      blog_toc: true
      categories_name: Categories
  - ezlinks  




extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://defnotfreddie.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fryderyk-%C5%82ysiak-b49426254/
    - icon: fontawesome/brands/github
      link: https://github.com/DnFreddie

copyright: "Copyright &copy; 2024 DnFreddie"

nav:
  - Home: index.md
  - Tags: tags.md
  - Blog:
      - blog/index.md  # Ensure this file exists

